name: flux-build
description: Build kustomize overlay with support for flux resources including HelmReleases

inputs:
  paths:
    description: "Comma separated paths to kustomize"
    required: true
    default: "."
  workers:
    description: "Concurrent helm template workers"
    required: false
    default: "1"
  fail-fast:
    description: "Abort early if any error occurs"
    required: false
    default: "false"
  allow-failure:
    description: "Specify if the action should fail if any errors occurs."
    required: false
    default: "false"
  cache-dir:
    description: "Path where artifacts may be stored"
    required: false
  registry-credentials:
    description: ''
    required: false
  kube-version:
    description: "Kubernetes version to test against. (Required for some helm charts which validate the kubernetes version)"
    required: false
    default: "1.27.0"

outputs:
  manifestFiles:
    description: "Comma separated paths to the built manifests containing all resources (per path input)"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/doodlescheduling/flux-build:v0'
