# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux-build" do
  version "3.1.3"

  on_macos do
    on_intel do
      sha256 "b5eb28fb9cd36285f0a7e7d44a7d38e47403e1a3eb8f66d82196f476795ab661"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b573f835fe2e638a79dd81f4fbd5be8dd961bc18b8b09d3c683f2a595a371971"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "080670501fcd5040afb9e6a320c0848ffd3c3e06b59f922dc660865cc377cfeb"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "42ec1750ba0a3506802a6d07d21499a14a1c5ea68814de996b82d758d3bc1ff7"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flux-build"
  desc "Build kustomize overlays with flux2 HelmRelease support"
  homepage "https://github.com/DoodleScheduling/flux-build"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux-build"

  # No zap stanza required

end
