# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux-build" do
  version "3.1.2"

  on_macos do
    on_intel do
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_darwin_amd64.tar.gz"
      sha256 "b11030d745d1fdd37fffd98ac510c64e479e6924df28b0c80fd5c7e5151c2eac"
    end
    on_arm do
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_darwin_arm64.tar.gz"
      sha256 "89aa04096690a2653b4284671bc7aed6ce1007401f806aca6e65a37808935964"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_linux_amd64.tar.gz"
      sha256 "412487ff395ca57f9851be8ed9c6f4e706df6488b10562d382be1c74420e8c25"
    end
    on_arm do
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_linux_arm64.tar.gz"
      sha256 "72d9347c178992a1a629c13629823c998fc897b3b6f407a2510e830774650db6"
    end
  end

  name "flux-build"
  desc "Build kustomize overlays with flux2 HelmRelease support"
  homepage "https://github.com/DoodleScheduling/flux-build"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux-build"

  # No zap stanza required

end
