# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux-build" do
  version "3.2.1"

  on_macos do
    on_arm do
      sha256 "5f615ca2910793e7c43b43fa8e815a5c57c286bd7a08e2a43ed0e0e24ee63f10"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4260df15229ff4ab66c27703f72e3e29ea895769b2ed3dcdbd50d33c7d9ffed6"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "508ed12ebdb2ed440b527b325df315f94323099e1cabbd2397deea23d0cc2e78"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "96562e2028a8da126d1ee08302e5d5b49728d9c8c87d74244fd10085a872dc62"
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v#{version}/flux-build_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flux-build"
  desc "Build kustomize overlays with flux2 HelmRelease support"
  homepage "https://github.com/DoodleScheduling/flux-build"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux-build"

  # No zap stanza required
end
