# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxBuild < Formula
  desc "Build kustomize overlays with flux2 HelmRelease support"
  homepage "https://github.com/DoodleScheduling/flux-build"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.1.4/flux-build_0.1.4_darwin_amd64.tar.gz"
      sha256 "a98f82ecaaf50907158ddb86eb681ac83fff3aad464041c7f2264991f741192e"

      def install
        bin.install "flux-build"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.1.4/flux-build_0.1.4_darwin_arm64.tar.gz"
      sha256 "203fff02cf562ed26d4df566283045cf9bb73a124aca95926cdde7e04d6c877e"

      def install
        bin.install "flux-build"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.1.4/flux-build_0.1.4_linux_arm64.tar.gz"
      sha256 "c6fccd3e1bfa7259302685cc161f5e9347a88d11695eb1c83404c73a046fef6f"

      def install
        bin.install "flux-build"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.1.4/flux-build_0.1.4_linux_amd64.tar.gz"
      sha256 "44b253fa2d379ed72567da902e8d88ed6825ba318b114d2d7fd44392ed1683de"

      def install
        bin.install "flux-build"
      end
    end
  end

  test do
    system "#{bin}/flux-build -h"
  end
end
