# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxBuild < Formula
  desc "Build kustomize overlays with flux2 HelmRelease support"
  homepage "https://github.com/DoodleScheduling/flux-build"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.0.8/flux-build_0.0.8_darwin_amd64.tar.gz"
      sha256 "6b859f7e9140a6c16cf74ee3946f598c774c0c35219dc58b37519252760304b1"

      def install
        bin.install "flux-build"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.0.8/flux-build_0.0.8_darwin_arm64.tar.gz"
      sha256 "04a9415dd915e9aeda5f2d785a6f692eb7ab5eff09665fad090a7371ff981311"

      def install
        bin.install "flux-build"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.0.8/flux-build_0.0.8_linux_amd64.tar.gz"
      sha256 "30e64b7df084e8f1eecbcf3d06e6203bef1802404cb4b9324ac7e368a63571f6"

      def install
        bin.install "flux-build"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/flux-build/releases/download/v0.0.8/flux-build_0.0.8_linux_arm64.tar.gz"
      sha256 "501e2118820adce6ee2c8bd442c47b54dda140ceb8a38197fa21b0823e7b8040"

      def install
        bin.install "flux-build"
      end
    end
  end

  test do
    system "#{bin}/flux-build -h"
  end
end
